name: hiro_anymetion
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_gen: ^5.8.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  dio: ^5.7.0
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1
  get_it: ^8.0.3
  get_storage: ^2.1.1
  webview_flutter: ^4.10.0
  firebase_messaging: ^15.2.0
  device_info_plus: ^11.2.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  intl:
  permission_handler: ^11.3.1
  sign_in_with_apple: ^6.1.4
  provider: ^6.1.2
  fluttertoast: ^8.2.10
  flutter_displaymode: ^0.6.0
  auto_animated: ^3.2.0
  http: ^1.2.2
  carousel_slider: ^5.0.0
  device_preview: ^1.2.0
  flutter_svg: ^2.0.17
  percent_indicator: ^4.2.4
  flutter_translate: ^4.1.0
  hero_animation: ^1.1.4
  progress_line: ^0.1.0
  animated_number: ^1.0.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  dependency_validator: ^4.1.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false

  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
